=== wojciech-piotrowiak/jrest/rest-root/04-jaxb/src/main/resources/jaxb/Bookstore.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.sages.com.pl/jrest/jaxb" xmlns="http://www.sages.com.pl/jrest/jaxb"
    attributeFormDefault="unqualified" elementFormDefault="qualified">
    <xs:element name="Bookstore">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Book" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:all>
                            <xs:element type="xs:string" name="Remark" maxOccurs="1" minOccurs="0" />
                            <xs:element type="xs:string" name="Title" />
                            <xs:element name="Authors">
                                <xs:complexType>
                                    <xs:sequence maxOccurs="unbounded" minOccurs="1">
                                        <xs:element name="Author">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element type="xs:string" name="First_Name" />
                                                    <xs:element type="xs:string" name="Last_Name" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:all>
                        <xs:attribute type="xs:string" name="ISBN" use="optional"/>
                        <xs:attribute type="xs:decimal" name="Price" />
                        <xs:attribute type="xs:string" name="Edition" use="optional"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Magazine" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="Title" />
                        </xs:sequence>
                        <xs:attribute type="xs:integer" name="Month" use="required" />
                        <xs:attribute type="xs:integer" name="Year" use="required" />
                        <xs:attribute type="xs:string" name="ISBN" use="optional" />
                        <xs:attribute type="xs:decimal" name="Price" use="optional" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== wojciech-piotrowiak/jrest/rest-root/04-jaxb/src/main/resources/pl/com/sages/jrest/jaxb/Bookstore.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Bookstore xmlns="http://www.sages.com.pl/jrest/jaxb" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
           xsi:schemaLocation="http://www.sages.com.pl/jrest/jaxb Bookstore.xsd">
    <Book ISBN="ISBN-0-13-713526-2" Price="85" Edition="3rd">
        <Title>W Pustyni i w Puszczy</Title>
        <Authors>
            <Author>
                <First_Name>Henryk</First_Name>
                <Last_Name>Sienkiewicz</Last_Name>
            </Author>
        </Authors>
    </Book>
    <Book ISBN="ISBN-0-13-815504-6" Price="100">
        <Remark>
            Buy this book bundled with "A First Course" - a great deal!
        </Remark>
        <Title>Database Systems: The Complete Book</Title>
        <Authors>
            <Author>
                <First_Name>Hector</First_Name>
                <Last_Name>Garcia-Molina</Last_Name>
            </Author>
            <Author>
                <First_Name>Jeffrey</First_Name>
                <Last_Name>Ullman</Last_Name>
            </Author>
            <Author>
                <First_Name>Jennifer</First_Name>
                <Last_Name>Widom</Last_Name>
            </Author>
        </Authors>
    </Book>
    <Magazine Month="9" Year="2016" Price="22">
        <Title>Å»agle</Title>
    </Magazine>
    <Magazine Month="1" Year="2015" ISBN="ISBN-0-13-815504-8">
        <Title>Programista</Title>
    </Magazine>
    <Magazine Month="2" Year="2015" Price="12">
        <Title>Programista</Title>
    </Magazine>
</Bookstore>
